name: INTEGRATION

on:
  push:
    branches: [ develop ]

jobs:
  Backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    services:
      mariadb:
        image: mariadb:12.1.2
        env:
          MARIADB_ROOT_PASSWORD: toor
          MARIADB_DATABASE: test
          MARIADB_USER: test
          MARIADB_PASSWORD: test
        ports:
          - 3306:3306

    env:
      BDD_HOST: 127.0.0.1
      BDD_NAME: test
      BDD_USER: test
      BDD_PASS: test

    steps:
      - name: Checkout
        uses: actions/checkout@4

      - name: Database check
        run: |
          sudo apt install -y mysql-client
          mysql -h 127.0.0.1 --port 3306 -u root -ptoor -e "SHOW DATABASES"

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install Dep
        run: npm i

      - name: Init and Populate BDD
        run: |
          npm run initbdd
          npm run populate

      - name: Run test and coverage
        run: npm run test:cov

      - name: Upload Coverage report
        uses: actions/upload-artifact@v4
        with:
          name: back-coverage-report
          path: backend/coverage
          retention-days: 1

  Frontend: 
    needs: [Backend]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout
        uses: actions/checkout@4

      - name: Start Backend
        run: |
          cd ..
          docker compose -f docker-compose-back-build.yml up -d
          docker ps -a

      - name: Wait for Backend to be ready
        uses: jakejarvis/wait-action@master
        with:
          time: '10s'

      - name: Check Backend
        if: success()
        run: curl http://127.0.0.1:12000

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Cypress E2E Install
        uses: cypress-io/github-action@v6
        with:
          runTests: false
          working-directory: frontend

      - name: Install Dep
        run: npm i

      - name: Cypress E2E Install
        uses: cypress-io/github-action@v6
        with:
          install: false
          start: npm run dev
          working-directory: frontend

      - name: Generate Coverage repport
        run: npm run cypress:cov

      - name: Upload Cy Screen - pour le fun
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshot
          path: frontend/cypress/screenshots
          retention-days: 1

      - name: Upload Cy Video
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: frontend/cypress/videos
          retention-days: 1
      
      - name: Upload Coverage report
        uses: actions/upload-artifact@v4
        with:
          name: cypress-coverage-report
          path: frontend/coverage
          retention-days: 1

      - name: Clean Docker
        if: always()
        run: |
          cd ..
          docker compose -f docker-compose-back-build.yml down